spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/DevDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASS}

  main:
    allow-bean-definition-overriding: true

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    check-template-location: true
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
    timeout: 60000

#  profiles:
#    active: alpha
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
#    timeout: 60000

#  profiles:
#    active: alpha
#  redis:
#    host: 54.180.127.156
#    port: 6379
#    timeout: 60000

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: false

  freemarker:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

    hibernate:
      format_sql: true
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8090

